name: Facebook

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.22.0'
        
    - run: flutter pub get
    
    - run: flutter build apk --release
        
    - uses: actions/upload-artifact@v4
      with:
        name: Facebook lite
        path: build/app/outputs/flutter-apk/Facebook-lite.apk